### ISSUE TITLE
Update readme.md with code of conduct, tags, objectives,tech stack, contributors...with images or gifs.

### ISSUE THREAD

**Issue by Pensuveze** [hctnm2/Beginner-Hacktoberfest#8]
@hctnm2   I want to contribute to this project. Please assign it to me .
Thanks..

**Comment by Pensuveze** [comment]
@hctnm2  can i now work on this issue ?

**Comment by hctnm2** [comment]
yes

**Comment by Pensuveze** [comment]
@hctnm2 Sir why you closed this issue ?

**Comment by hctnm2** [comment]
@Pensuveze People Are getting confused because of this u can make ur changes and make pull request i will accept
